[2024-12-26T09:02:47.511+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T09:02:47.560+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream_vehicle_alerts_processing.load_to_destination scheduled__2024-12-25T00:00:00+00:00 [queued]>
[2024-12-26T09:02:47.580+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream_vehicle_alerts_processing.load_to_destination scheduled__2024-12-25T00:00:00+00:00 [queued]>
[2024-12-26T09:02:47.582+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-26T09:02:47.615+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_to_destination> on 2024-12-25 00:00:00+00:00
[2024-12-26T09:02:47.622+0000] {standard_task_runner.py:72} INFO - Started process 1137 to run task
[2024-12-26T09:02:47.631+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stream_vehicle_alerts_processing', 'load_to_destination', 'scheduled__2024-12-25T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/streamVehiculeAlertsProcessing.py', '--cfg-path', '/tmp/tmpap43tru8']
[2024-12-26T09:02:47.639+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask load_to_destination
[2024-12-26T09:02:47.765+0000] {task_command.py:467} INFO - Running <TaskInstance: stream_vehicle_alerts_processing.load_to_destination scheduled__2024-12-25T00:00:00+00:00 [running]> on host 3096e710f899
[2024-12-26T09:02:47.971+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stream_vehicle_alerts_processing' AIRFLOW_CTX_TASK_ID='load_to_destination' AIRFLOW_CTX_EXECUTION_DATE='2024-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-25T00:00:00+00:00'
[2024-12-26T09:02:47.977+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T09:03:33.539+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-12-26T09:03:33.549+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T09:03:33.557+0000] {process_utils.py:132} INFO - Sending 15 to group 1137. PIDs of all processes in the group: [1139, 1137]
[2024-12-26T09:03:33.560+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1137
[2024-12-26T09:03:33.568+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-26T09:03:33.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T09:03:33.748+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1137, status='terminated', exitcode=0, started='09:02:46') (1137) terminated with exit code 0
[2024-12-26T09:03:33.751+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1139, status='terminated', started='09:02:47') (1139) terminated with exit code None
